### ISSUE TITLE
syntaxError

### ISSUE THREAD

**Issue by ghost** [mdbetancourt/Tebless#3]
* Tebless version:1.2.3
* Python 2.7
* Operating System:osx10.13

### Description
``` sh
Traceback (most recent call last):
  File "tebless_test.py", line 1, in <module>
    from tebless.widgets import Window, Input
  File "/usr/local/lib/python2.7/site-packages/tebless/widgets/__init__.py", line 5, in <module>
    from .window import Window
  File "/usr/local/lib/python2.7/site-packages/tebless/widgets/window.py", line 20, in <module>
    from tebless.devs import Widget, echo
  File "/usr/local/lib/python2.7/site-packages/tebless/devs/__init__.py", line 11
    echo = functools.partial(print, end='', flush=True)
                                 ^
SyntaxError: invalid syntax
```

**Comment by mdbetancourt** [comment]
sorry, this library only has support for python 3
