### ISSUE TITLE
No module named 'events'

### ISSUE THREAD

**Issue by KuSi833** [mdbetancourt/Tebless#5]
* Tebless version: 1.2.3
* Python version: 3.9.5
* Operating System: Windows 10

### Description

I was trying to import the Window widget.

### What I Did

For the following code:

```python
from tebless.widgets import Label, Window, Input
```

I get the following error:
```
Traceback (most recent call last):
  File "F:\Coding\Projects\sound-recognition\pico_test.py", line 1, in <module>
    from tebless.widgets import Label, Window, Input
  File "C:\ProgramData\Anaconda3\envs\blessed\lib\site-packages\tebless\widgets\__init__.py", line 5, in <module>
    from .window import Window
  File "C:\ProgramData\Anaconda3\envs\blessed\lib\site-packages\tebless\widgets\window.py", line 18, in <module>
    from events import Events
ModuleNotFoundError: No module named 'events'
```

Am I missing some specific module to make this work on Windows, or was it never supported on Windows?
I tried installing events but then I only got further errors.

**Comment by evprkr** [comment]
`pip3 install events` fixed it for me.

**Comment by mdbetancourt** [comment]
this lib require events package but i have my own version i added it to the requirements.txt file
